### ISSUE TITLE
merger doesn't start without setting start block

### ISSUE THREAD

**Issue by matthewdarwin** [EOS-Nation/firehose-antelope#27]
Nov 26 17:11:49 eos-sfdm64a nodeos[24163]: Fatal error in app merger:
Nov 26 17:11:49 eos-sfdm64a nodeos[24163]: expecting to start at block 0 but got block 2 (and we have no previous blockID to align with..). First streamable block is configured to be: 1

genesis json should be probably be stored in block 1?  Discuss with SF team.

**Comment by fschoell** [comment]
seems like the first streamable block is 2 for antelope chains (reads like the deepmind plugin only starts logging from block 2?)

```
	// This should be the block number of the first block that is streamable using Firehose,
	// for example on Ethereum it's set to `0`, the genesis block's number while on EOSIO it's
	// set to 2 (genesis block is 1 there but our instrumentation on this chain instruments
	// only from block #2).
```

**Comment by fschoell** [comment]
#31 fixes the start up by setting the default first streamable block to 2. 

Not sure how much work it is to include block 1 and if it's worth the effort.

**Comment by matthewdarwin** [comment]
Not sure.  SF team changed Ethereum to start at block 0 (previously it was 1).

**Comment by fschoell** [comment]
first streamable block is set to 2 again
