### ISSUE TITLE
Can't stream using negative start block

### ISSUE THREAD

**Issue by DenisCarriere** [EOS-Nation/firehose-antelope#41]
## Question

When using `-start-block` it only starts from the initial block, but not the "end of the current blocks"

How do you stream only the latest blocks using a negative value?

Also tried using `-stop-block` and it throws an error since it doesn't allow negatives

Bug 🐛  or feature 🔨 ?

## CLI

>  -s, --start-block int                      Start block to stream from. Defaults to -1, which means the initialBlock of the first module you are streaming (default -1)
>   -t, --stop-block string                    Stop block to end stream at, inclusively. (default "0")

## ❌ Can't stream using negative start block beyond initial block

```yaml
modules:
  - name: map_transfers
    kind: map
    inputs:
      - source: sf.antelope.type.v2.Block
    output:
      type: proto:antelope.eosio.token.v1.TransferEvents
```

https://github.com/EOS-Nation/substreams-antelope/blob/690be1d05eb8c4438102369497cc1f014255846c/substreams/eosio.token/substreams.yaml#L22-L28

```
$ substreams run -e eos.firehose.eosnation.io:9001 https://eos.mypinata.cloud/ipfs/QmbttxBK9FbV8E8g8g8jp8rpYDvK8QzEwSx4bQmafngXpJ map_transfers -s -1000
Connected - Progress messages received: 0 (0/sec)
Backprocessing history up to requested target block 18446744073709550616:
(hit 'm' to switch mode)

Error: rpc error: code = InvalidArgument desc = validate request: negative start block -1000 is not accepted
```

## ❌ Stop block must be positive integer

```
$ substreams run -e eos.firehose.eosnation.io:9001 https://eos.mypinata.cloud/ipfs/QmbttxBK9FbV8E8g8g8jp8rpYDvK8QzEwSx4bQmafngXpJ map_transfers -t -1000       
Error: stop block: end block is invalid: strconv.ParseUint: parsing "-1000": invalid syntax
```

**Comment by fschoell** [comment]
this is working now (implemented on the Substreams repository)
