### ISSUE TITLE
`bool` encoding

### ISSUE THREAD

**Issue by YaroShkvorets** [EOS-Nation/firehose-antelope#71]
Decoding `db_op.new_data_json` JSON, ran into an issue that boolean values are encoded as 0/1 as opposed to false/true.

Example: `atomicassets::setcoldata` action updating `collections` table: https://eos.eosq.eosnation.io/tx/026601c512c54841184553eaa6d50daa70e927386ea4530dc18e51efee6e1035

Abi:
```
{
            "name": "collections_s",
            "base": "",
            "fields": [
                {
                    "name": "collection_name",
                    "type": "name"
                },
                {
                    "name": "author",
                    "type": "name"
                },
                {
                    "name": "allow_notify",
                    "type": "bool"
                },
                {
                    "name": "authorized_accounts",
                    "type": "name[]"
                },
                {
                    "name": "notify_accounts",
                    "type": "name[]"
                },
                {
                    "name": "market_fee",
                    "type": "float64"
                },
                {
                    "name": "serialized_data",
                    "type": "uint8[]"
                }
            ]
        },
```

Receiving from firehose (see `allow_notify`):
```
{
    "allow_notify": 1,
    "author": "steph",
    "authorized_accounts": ["steph", "atomicdropsx", "unpack.gems"],
    "collection_name": "eosmemewars1",
    "market_fee": "0.10000000000000001",
    "notify_accounts": [],
    "serialized_data": [4, 18, 77, 101, 109, <skip> , 34, 58, 34, 34, 125]
}
```

Any reason why it's not boolean?

**Comment by fschoell** [comment]
This is weird. The decoder correctly decodes the value to "true". So maybe this is happening on some (un-)marshalling step. Do you know of an action that contains a boolean value in it's data? Would like to check if this is a common thing with all nested boolean values or if it's only impacting the decoded table data.

**Comment by YaroShkvorets** [comment]
> Do you know of an action that contains a boolean value in it's data? 

You mean boolean action param?
Here's [one](https://eos.eosq.eosnation.io/tx/a779ab469590d0ef15882570edb73efe845e8cd2e8c8cbc198b84ba3896187c5)

Looks like it's also encoded as `1`.

**Comment by fschoell** [comment]
Hmm ok I'll need to take a deeper look into this. Do you know if it's consistent behaviour to encode nested json data into 0/1 or does this impact only certain actions?

**Comment by YaroShkvorets** [comment]
Looks consistent. Here's `eosio::deletegatebw` call: https://eos.eosq.eosnation.io/tx/bd1bd84da20a7028c14d3404a544fe86a91d7e423ab6db64d7a2cea18f927a3a

**Comment by fschoell** [comment]
```
Jul 07 10:37:50 eos-sfdm41 nodeos[1519058]: 2023-07-07T10:37:50.772Z DEBG (codec) decoding action {"action": "eosio:delegatebw", "global_sequence": 358638274958}
Jul 07 10:37:50 eos-sfdm41 nodeos[1519058]: 2023-07-07T10:37:50.772Z DEBG (codec) found ABI and action definition, performing decoding {"action": "eosio:delegatebw", "global_sequence": 358638274958}
Jul 07 10:37:50 eos-sfdm41 nodeos[1519058]: 2023-07-07T10:37:50.772Z DEBG (codec) successfully decoded action data {"action": "eosio:delegatebw", "json_data": "{\"from\":\"kingparallax\",\"receiver\":\"kingparallax\",\"stake_cpu_quantity\":\"27.9807 EOS\",\"stake_net_quantity\":\"0.0000 EOS\",\"transfer\":0}"}
```

**Comment by fschoell** [comment]
Ok so I copied out the decoding part, ran it locally with a delegatebw action and it is properly decoding the boolean value to true/false instead of 0/1. This is weird. 

Looking at the [battlefield-eosio repository](https://github.com/streamingfast/battlefield-eosio) it seems like the boolean decoding always has been to 0/1 (it's how nested json strings with booleans are encoded in the golden.json files which were used to test against with linediff).

**Comment by YaroShkvorets** [comment]
OK, so we are keeping it this way?

**Comment by matthewdarwin** [comment]
I assume yes, unless you get [maoueh](https://github.com/maoueh) to say otherwise.

**Comment by YaroShkvorets** [comment]
[Related commit](https://github.com/eoscanada/eos-go/commit/83019809d50bf149692afd461796bd74681e7dc3) where they changed the decoding to byte

Then [they added](https://github.com/eoscanada/eos-go/commit/ba2ce9b983467d916eacf8216c344d04af9c9450) `fitNodeos` flag.

So they did it to align with nodeos.

Is there any downside if we just decode it as true/false?

**Comment by matthewdarwin** [comment]
I love we can find the code change for that.

**Comment by fschoell** [comment]
Setting fitNodeos to false has other implications on parsings, like int128 getting parsed into a string instead of a number. Not sure what the impacts are when changing that. 

Seems like Matthieu doesn't know either.

**Comment by fschoell** [comment]
@YaroShkvorets is this still relevant or should we close the issue?

**Comment by YaroShkvorets** [comment]
I guess we can close it.
