### ISSUE TITLE
error message says acme

### ISSUE THREAD

**Issue by matthewdarwin** [EOS-Nation/firehose-antelope#87]
I saw this message:

 Error: config file "/etc/dfuse/config.yml" not found. Did you 'fireacme init'?

The fact the config file is missing is my problem, but the error shouldn't say fireacme.

**Comment by fschoell** [comment]
This error is not coming from firehose-antelope, the relevant code has been moved to firehose-core see [here](https://github.com/streamingfast/firehose-core/blob/cff94677bea714fc9d79c0c7316c2f1a1d617c8c/setup.go#L32).

**Comment by matthewdarwin** [comment]
Thanks. Created issue in firehose-core for this.
